apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio-ismael
  namespace: argocd
  annotations:
    # Definimos el alias
    argocd-image-updater.argoproj.io/image-list: myimg=iferlop/portfolio_app
    # Usamos el alias para la estrategia de actualización (DIGEST es mejor para tags fijos como latest)
    argocd-image-updater.argoproj.io/myimg.update-strategy: digest
    # Usamos el alias para mapear los valores de Helm
    argocd-image-updater.argoproj.io/myimg.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/myimg.helm.image-tag: image.tag
    # Permitimos el tag latest
    argocd-image-updater.argoproj.io/myimg.allow-tags: regexp:^latest$
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Vixtinity/portfolioreact.git
    targetRevision: main
    path: deploy/miportfolio
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: portfolio-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true